### ISSUE TITLE
all: add R environment

### ISSUE THREAD

**Issue by cvanderaa** [UCLouvain-CBIO/SCP.replication#17]
Add for each vignette a corresponding R environment that will allow to reproduce the vignette even if there are changes in the dependencies. 

[`renv`](https://github.com/rstudio/renv) is probably a good tool to perform this.

**Comment by lgatto** [comment]
This is a technically elaborated approach and, if it works (i.e. integrates well with github), would be great. Another approach is to trick the package/website builder by having a dummy vignette to compile dynamically (so that the vignette gets referenced) and then replace it by the pre-compiled/static html version. This can be automated with a simple `Makefile`.

**Comment by cvanderaa** [comment]
List of vignettes to add `renv`
- [x] schoof2021
- [x] SCoPE2
- [x] liang2020
- [x] zhu2019EL
